# Project information
site_name: RestoBook Docs

# Repository
repo_name: solopov-av-edu/RestoBook-Docs
repo_url: https://github.com/solopov-av-edu/RestoBook-Docs

theme:
  custom_dir: 'theme'
  name: material
  palette:
      # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  language: ru
  features:
    - navigation.instant # Мгновенная загрузка
    - navigation.tracking # Когда отслеживание привязки включено, URL-адрес в адресной строке автоматически обновляется активным привязкой, как выделено в оглавлении. 
    - navigation.expand # Автоматическое открытие подразделов на панели слева
    - navigation.path # Над заголовком каждой страницы отображается путь
    - navigation.top # Кнопка «назад-вверх»
    - navigation.footer # Переключение кнопками предыдущей/следующей страницы в футере
    - navigation.tabs # Навигационные вкладки
    # - navigation.sections # Отображение верхних вкладок на панели слева
    - navigation.indexes # Скрыть дублирование заголовка на панели слева.
    - toc.integrate # Интеграция подразделов в панель слева
    - toc.follow # Автоматическая прокрутка боковой панели при прокрутке
    - search.highlight # Подсветка вхождений в тексте
    - search.suggest # Автозавершение поискового запроса
    - content.code.copy # Кнопка копирования кода
    

markdown_extensions:
  # - lightgallery
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      toc_depth: 3
      permalink: true
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      auto_append: 
      - docs/abbreviations.md

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - swagger-ui-tag
  - build_plantuml:
      render: 'server' # or "local" for local rendering
      bin_path: '/usr/local/bin/plantuml' # ignored when render: server
      server: 'http://www.plantuml.com/plantuml' # official plantuml server
      disable_ssl_certificate_validation: true # for self-signed and invalid certs
      output_format: 'svg' # or "png"
      diagram_root: 'docs/diagrams' # should reside under docs_dir
      output_folder: 'out'
      input_folder: 'src'
      input_extensions: '' # comma separated list of extensions to parse, by default every file is parsed
  - enumerate-headings:
      exclude:
        - index.md
        - glossary.md
  # - print-site:
  #     path_to_pdf: "assets/test.pdf"
  - glightbox

nav:
  - Домашняя страница:
    - index.md
  - Документация:
    - glossary.md
    - general info.md
    - goals.md
    - characteristics.md
    - business process.md
    - requirements.md
    - model.md
    - architecture.md
    - uiux.md
    - api.md
  - Задачи:
    - tasks/registration_client.md
    - tasks/registration_user.md
    - tasks/auth_client.md
    - tasks/auth_user.md
    - tasks/booking_table.md