@startuml

skinparam linetype ortho

Entity Клиент {
  *Название
  *ИНН
  *КПП
  *ОГРН
  *Юридический адрес
  *Имя директора
  *Годовой оборот
}

Enum Тип_бизнеса {
  Ресторан
  Бар
  Кафе
  Столовая
  Закусочная
}

Entity Представитель_клиента {
  *Имя
  *Фамилия
  *Телефон
  *Email
}

Entity Тариф {
  *Название
  *Комиссия
}

Entity Индивидуальный_Тариф {
  *Доп. условия
  *Скидка
}

Enum Статус_клиента{
  Новый
  Зарегистрирован
  Активирован
  Удален
}

Entity Ресторан {
  *Название
  *Адрес
  *Описание
  *Телефон
  *Вместимость
}

Enum Тип_кухни {
  Русская 
  Итальянская 
  Американская 
  Японская 
  Китайская 
  Узбекская 
  Кавказская 
  Арабская 
  Индийская 
  Австрийская 
}

Entity Столик {
  *Вместимость
  *Номер
  Расположение
  Особые отметки
}

Enum Статус_ресторана {
  Доступен
  Недоступен
}

Enum Статус_столика {
  Доступен
  Недоступен
}

Entity Расписание {
  *День недели
  *Время начала работы
  *Время окончания работы
  *Дата
}

Entity Пользователь {
  *Телефон
  *Имя
  Email
}

Enum Статус_пользователя {
  Новый
  Зарегистрирован
  Удален
}

Entity Бронирование {
  *Название ресторана
  *Адрес ресторана
  *Номер столика
  *Дата и время начала бронирования
  *Дата и время окончания бронирования
  *Количество человек
}

Enum Статус_бронирования {
  Не подтверждена
  Подтверждена
  Отклонена
  Отменена
  Завершена
}


Клиент *--"1,*" Представитель_клиента
Клиент "0,*" --> "0,1" Тариф
Клиент "*" --> "1" Статус_клиента
Клиент "1"*--"0,*" Ресторан
Клиент "*" --> "0,1" Тип_бизнеса

Тариф ^-- Индивидуальный_Тариф

Ресторан *--"1,*" Столик
Ресторан "*" --> "1,5" Тип_кухни
Ресторан "*" --> "1" Статус_ресторана
Ресторан *--"1,*" Расписание

Столик "*" --> "1" Статус_столика

Пользователь "*" --> "1" Статус_пользователя
Пользователь *-- "0,*" Бронирование

Бронирование "*" --> "1" Статус_бронирования
Бронирование "0,*" --> "1,* " Столик



@enduml